// 3D chalk art portfolio. Add a new piece by copying a block and dropping the
// image into src/assets/img/chalk/. `featured: true` surfaces it on the homepage.
export default [
  {
    title: "Hungry Hungry Hippos: Robot Battle",
    image: "/assets/img/chalk/hungry-hippos-2025.jpg",
    alt: "Hungry Hungry Hippos robot 3D chalk art, a 15ft x 25ft interactive street painting by Chris Carlson at the 2025 Denver Chalk Art Festival",
    location: "Denver Chalk Art Festival, Denver, CO",
    dimensions: "15ft x 25ft",
    featured: true,
  },
  {
    title: "Elder Dragon",
    image: "/assets/img/chalk/elder-dragon.jpg",
    alt: "Elder Dragon 3D chalk art illusion bursting through the pavement, a 15ft x 30ft street painting by Chris Carlson commissioned by Riot Games in Santa Monica, California",
    location: "Santa Monica, CA",
    dimensions: "15ft x 30ft",
    client: "Riot Games",
    featured: true,
  },
  {
    title: "Mech Cat vs. Bird",
    image: "/assets/img/chalk/mech-cat-vs-bird.webp",
    alt: "3D chalk art of a giant mech cat battling a bird, a 10ft x 24ft street painting by Chris Carlson in Denver, Colorado",
    location: "Denver, CO",
    dimensions: "10ft x 24ft",
    featured: true,
  },
  {
    title: "Toy Story",
    image: "/assets/img/chalk/toy-story.jpg",
    alt: "Toy Story 3D chalk art illusion, a 10ft x 22ft street painting by Chris Carlson at Epcot, Walt Disney World in Orlando, Florida",
    location: "Epcot, Orlando, FL",
    dimensions: "10ft x 22ft",
    client: "Walt Disney World",
    featured: true,
  },
  {
    title: "Emperor's New Groove",
    image: "/assets/img/chalk/emperors-new-groove.jpg",
    alt: "Emperor's New Groove 3D chalk art, a 10ft x 30ft anamorphic street painting by Chris Carlson at Epcot, Walt Disney World in Orlando, Florida",
    location: "Epcot, Orlando, FL",
    dimensions: "10ft x 30ft",
    client: "Walt Disney World",
    featured: true,
  },
  {
    title: "Ferrari Challenge",
    image: "/assets/img/chalk/ferrari-challenge.webp",
    alt: "Ferrari Challenge 3D chalk art, a 24ft x 40ft branded street painting by Chris Carlson in Austin, Texas",
    location: "Austin, TX",
    dimensions: "24ft x 40ft",
    client: "Ferrari",
    featured: true,
  },
  {
    title: "Hungry Otter",
    image: "/assets/img/chalk/hungry-otter.webp",
    alt: "3D chalk art of a hungry otter bursting from the pavement, a 10ft x 20ft street painting by Chris Carlson in Tallahassee, Florida",
    location: "Tallahassee, FL",
    dimensions: "10ft x 20ft",
    featured: true,
  },
  {
    title: "Fly Away!",
    image: "/assets/img/chalk/fly-away.webp",
    alt: "3D chalk street painting of a soaring scene titled Fly Away, 10ft x 20ft, by Chris Carlson in Yellowstone, Montana",
    location: "Yellowstone, MT",
    dimensions: "10ft x 20ft",
    featured: true,
  },
  {
    title: "Jaws",
    image: "/assets/img/chalk/jaws.webp",
    alt: "Jaws shark 3D chalk art illusion, a 5ft x 8ft street painting by Chris Carlson in Denver, Colorado",
    location: "Denver, CO",
    dimensions: "5ft x 8ft",
  },
  {
    title: "Dolphin Ride",
    image: "/assets/img/chalk/dolphin-ride.webp",
    alt: "3D chalk art of a dolphin leaping from the street, a 10ft x 20ft anamorphic painting by Chris Carlson in Columbia, Missouri",
    location: "Columbia, MO",
    dimensions: "10ft x 20ft",
  },
  {
    title: "Hungry Hungry Hippos",
    image: "/assets/img/chalk/hungry-hippos.webp",
    alt: "Hungry Hungry Hippos 3D chalk art, a 10ft x 10ft interactive street painting by Chris Carlson in Denver, Colorado",
    location: "Denver, CO",
    dimensions: "10ft x 10ft",
  },
  {
    title: "Alien Offering",
    image: "/assets/img/chalk/alien-offering.webp",
    alt: "Alien Offering 3D chalk art, a 10ft x 20ft anamorphic street painting by Chris Carlson in Panama City, Florida",
    location: "Panama City, FL",
    dimensions: "10ft x 20ft",
  },
  {
    title: "The Big Lebowski",
    image: "/assets/img/chalk/big-lebowski.webp",
    alt: "The Big Lebowski 3D chalk art illusion, a 10ft x 20ft street painting by Chris Carlson in Marietta, Georgia",
    location: "Marietta, GA",
    dimensions: "10ft x 20ft",
  },
  {
    title: "Don't Look Down",
    image: "/assets/img/chalk/dont-look-down.webp",
    alt: "Don't Look Down 3D chalk art of a hole in the ground illusion, 8ft x 14ft, by Chris Carlson in Denver, Colorado",
    location: "Denver, CO",
    dimensions: "8ft x 14ft",
  },
  {
    title: "Lava Lamp Cat",
    image: "/assets/img/chalk/lava-lamp-cat.webp",
    alt: "Lava Lamp Cat interactive 3D chalk art illusion by Chris Carlson",
    location: "Interactive piece",
    dimensions: "",
  },
  {
    title: "Tiger Hoverboard",
    image: "/assets/img/chalk/tiger-hoverboard.jpg",
    alt: "Interactive 3D chalk art of a tiger on a hoverboard by Chris Carlson",
    location: "Columbia, MO",
    dimensions: "",
  },
  {
    title: "Magical Alien",
    image: "/assets/img/chalk/magical-alien.jpg",
    alt: "Magical alien interactive 3D chalk art illusion by Chris Carlson",
    location: "Interactive piece",
    dimensions: "",
  },
  {
    title: "Shark Attack",
    image: "/assets/img/chalk/shark.jpg",
    alt: "Interactive 3D chalk art of a shark breaking through the ground by Chris Carlson",
    location: "Interactive piece",
    dimensions: "",
  },
];
